apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: default
data:
  init-databases.sql: |
    -- Create vehicle_db
    CREATE DATABASE vehicle_db;
    GRANT ALL PRIVILEGES ON DATABASE vehicle_db TO postgres;

    -- Create maintenance_db
    CREATE DATABASE maintenance_db;
    GRANT ALL PRIVILEGES ON DATABASE maintenance_db TO postgres;

    -- Create driver_db
    CREATE DATABASE driver_db;
    GRANT ALL PRIVILEGES ON DATABASE driver_db TO postgres;
